ArtBot:
  StableDiffusion:
    Token:
    BaseUrl:
    PrefixUri:
    Version:
    HttpDebug:
    ProxyURL:

ChatBot:
  # OpenAI
  ChatGPT:
    OpenAPIKey:
    Organization:
    HttpDebug:
    BaseURL:
    APIType:
    APIVersion:

  # 讯飞云
  XFYun:
    WebSocketURL: ws://spark-api.xf-yun.com/v1.1/chat
    AppID:
    APISecret:
    APIKey:
