Server:
  Name: RobotChat
  Host: 0.0.0.0
  Port: 8080
  Timeout: 30000

Auth:
  Account: user
  Password: pass

Database:
  Driver: postgres
  DSN: host=localhost user=michaelhu password=robotchat dbname=robotchat port=5432 sslmode=disable TimeZone=UTC


ArtBot:
  Channel: stableDiffusion
  StableDiffusion:
    Token:
    BaseUrl: http://127.0.0.1:7861
    PrefixUri:
    Version:
    HttpDebug:
    ProxyUrl:


  # 异步队列
  Queue:
    Driver: redis
    # 异步操作回调通知
    NotifyUrl: http://127.0.0.1:8080/api/v1/webhook/queue/notify
    Redis:
      Addr: 127.0.0.1:6379
      ClientName: ArtBot
      Username:
      Password:
      DB: 1
      MaxRetries: 3
  Log:
    Driver: zap
    Env: develop
    InfoLog: ./artBot_info.log
    ErrorLog: ./artBot_error.log

ChatBot:
  Channel: openAI
  # OpenAI
  ChatGPT:
    OpenAPIKey: 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
    Organization: 55hudong
    Model: ada:ft-55hudong-2023-06-15-05-51-27
    HttpDebug: true
    BaseURL: https://chat.kxllen.com/v1
    APIType:
    APIVersion:

  # 讯飞云
  XFYun:
    WebSocketURL: ws://spark-api.xf-yun.com/v1.1/chat
    AppID: 513456d0
    APISecret: ZjczYTFhODk5ZGUyNzA3MjU4ZmIzMjVk
    APIKey: 065c300a5966808291e3f5f1f94b5efa

  Queue:
    Driver: redis
    # 异步操作回调通知
    NotifyUrl: http://127.0.0.1:8080/api/v1/webhook/queue/notify
    Redis:
      Addr: 127.0.0.1:6379
      ClientName: ChatBot
      Username:
      Password:
      DB: 2
      MaxRetries: 3
  Log:
    Driver: zap
    Env: develop
    InfoLog: ./chatBot_info.log
    ErrorLog: ./chatBot_error.log

