ArtBot:
  StableDiffusion:
    BaseUrl:
    PrefixUri:
    Version:
    HttpDebug:
    ProxyURL:

ChatBot:
  ChatGPT:
    OpenAPIKey: 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
    Organization: 55hudong
    HttpDebug: true
    ProxyURL: https://chat.kxllen.com
