version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-robotChat
    environment:
      POSTGRES_USER: robotchat
      POSTGRES_PASSWORD: robotchatpw
      POSTGRES_DB: robotChat
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "54321:5432"
    networks:
      - robotChat-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U robotChat" ]
      interval: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: redis-robotChat
    ports:
      - "63791:6379"
    networks:
      - robotChat-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 5s
      retries: 5

  server:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    container_name: robotChat-server
    volumes:
      - ./etc/config.yaml:/app/etc/config.yaml
    ports:
      - "8080:8080"
    networks:
      - robotChat-network
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    # healthcheck:
      # test: [ "CMD", "nc", "-z", "localhost", "8080" ]
      # interval: 30s
      # timeout: 5s
      # retries: 5

  network-tools:
    image: nicolaka/netshoot:latest
    container_name: network-tools-robotChat
    command: sleep infinity
    networks:
      - robotChat-network

networks:
  robotChat-network:
    driver: bridge


