Server:
  Name: RobotChat
  Host: 0.0.0.0
  Port: 8080
  Timeout: 30000

Auth:
  Account: user
  Password: pass

Database:
  Driver: postgres
  DSN: host=Michaels-MacBook-Pro.local user=robot password=robotchat dbname=robotchat port=54321 sslmode=disable TimeZone=UTC


ArtBot:
  Channel: stableDiffusion
  StableDiffusion:
    Token:
    BaseUrl: http://Michaels-MacBook-Pro.local:7861
    PrefixUri:
    Version:
    HttpDebug:
    ProxyUrl:


  # 异步队列
  Queue:
    Driver: redis
    # 异步操作回调通知
    NotifyUrl: http://Michaels-MacBook-Pro.local:8080/api/v1/webhook/queue/notify
    Redis:
      Addr: Michaels-MacBook-Pro.local:63791
      ClientName: ArtBot
      Username:
      Password:
      DB: 1
      MaxRetries: 3
  Log:
    Driver: zap
    Env: develop
    InfoLog: ./artBot_info.log
    ErrorLog: ./artBot_error.log

ChatBot:
  Channel: openAI
  # OpenAI
  ChatGPT:
    OpenAPIKey: 
    Organization: 
    Model: ada:ft-2023-06-15-05-51-27
    HttpDebug: true
    BaseURL: 
    APIType:
    APIVersion:

  # 讯飞云
  XFYun:
    WebSocketURL: 
    AppID: 
    APISecret: 
    APIKey: 

  Queue:
    Driver: redis
    # 异步操作回调通知
    NotifyUrl: http://Michaels-MacBook-Pro.local:8080/api/v1/webhook/queue/notify
    Redis:
      Addr: Michaels-MacBook-Pro.local:63791
      ClientName: ChatBot
      Username:
      Password:
      DB: 2
      MaxRetries: 3
  Log:
    Driver: zap
    Env: develop
    InfoLog: ./chatBot_info.log
    ErrorLog: ./chatBot_error.log

