Server:
  Name: RobotChat
  Host: 0.0.0.0
  Port: 8080
  Timeout: 30000

Auth:
  Account: user
  Password: pass

Database:
  Driver: postgres
  DSN: host=host.docker.internal user=robotchat password=robotchatpw dbname=robotchat port=54321 sslmode=disable TimeZone=UTC


ArtBot:
  Channel: stableDiffusion
  StableDiffusion:
    Token:
    BaseUrl: http://host.docker.internal:7861
    PrefixUri:
    Version:
    HttpDebug:
    ProxyUrl:


  # 异步队列
  Queue:
    Driver: redis
    # 异步操作回调通知
    NotifyUrl: http://host.docker.internal:8080/api/v1/webhook/queue/notify
    Redis:
      Addr: host.docker.internal:63791
      ClientName: ArtBot
      Username:
      Password:
      DB: 1
      MaxRetries: 3
  Log:
    Driver: zap
    Env: develop
    InfoLog: ./logs/chatBot/info.log
    ErrorLog: ./logs/chatBot/error.log

ChatBot:
  Channel: openAI
  # OpenAI
  ChatGPT:
    OpenAPIKey: 
    Organization: 
    Model: ada:ft-2023-06-15-05-51-27
    HttpDebug: true
    BaseUrl: 
    APIType:
    APIVersion:

  # 讯飞云
  XFYun:
    WebSocketUrl: 
    AppId: 
    APISecret: 
    APIKey: 
  # 清华GLM LLM
  THUDM_GLM:
    BaseUrl: http://127.0.0.1:8000
    HttpDebug: true

  Queue:
    Driver: redis
    # 异步操作回调通知
    NotifyUrl: http://host.docker.internal:8080/api/v1/webhook/queue/notify
    Redis:
      Addr: host.docker.internal:63791
      ClientName: ChatBot
      Username:
      Password:
      DB: 2
      MaxRetries: 3
  Log:
    Driver: zap
    Env: develop
    InfoLog: ./logs/chatBot/info.log
    ErrorLog: ./logs/chatBot/error.log

